name: Deploy
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "src"

      - name: NPM install
        run: npm install

      - name: Build
        run: cd src && ng build && cd ..

      - name: Checkout deployment branch
        uses: actions/checkout@v2
        with:
          path: "dist"
          ref: "github-pages"
          
      - name: Copy files
        run: |
          rm dist/*
          cp -r src/dist/lucypoulton-dot-net/* dist
          cp dist/index.html dist/404.html
          echo "lucypoulton.net" > dist/CNAME
          git commit -am "${{ github.event.commits[0].id }}: ${{github.events.commits[0].message }}"
          git push origin github-pages
        
