name: Deploy
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "src"
          
      - name: Build
        run: cd src && npm install && npx ng build && cd ..

      - name: Checkout deployment branch
        uses: actions/checkout@v2
        with:
          path: "dist"
          ref: "github-pages"
          
      - name: Copy files
        run: |
          cd dist
          rm -rf . -v !(".git")
          cp -r ../src/dist/lucypoulton-dot-net/* .
          cp index.html 404.html
          echo "lucypoulton.net" > CNAME
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-action@lucypoulton.net"
          git add .
          git commit -am "${{ github.event.commits[0].id }}: ${{github.event.commits[0].message }}"
          git push origin github-pages
        
